// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpzvrwziwwyyrhjbchqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wenZyd3ppd3d5eXJoamJjaHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTIzMjUsImV4cCI6MjA1NzkyODMyNX0.ouzNwP4rCQTRgS_IQzUsviyfPtU_7hPf6UIBJ2u0ZQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);